#!/bin/bash
#
# (c) Stephen Bates, Eideticom 2018
#
# A helper script that I will try to keep up to date to build the
# latest and greatest p2pdma kernel using known good .configs.

CONFIG=${CONFIG:-./useful-configs/config-x86_64-p2pdma}
REMOTE_BRANCH=${REMOTE_BRANCH:-v5.8.14}
REMOTE=${REMOTE:-git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git}

export CONFIG
export REMOTE_BRANCH
export REMOTE

PATCH=patches/p2pdma \
  ICECC=no \
  THREADS=128 \
  ./scripts/build-kernel-debrpm
