name: linux-tools-docker-test

on:
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-docker-test:
    name: ubuntu-docker-test
    runs-on: ubuntu-latest
    steps:
    - name: check out code using action/checkout
      uses: actions/checkout@v2
    - name: build package via the Dockerfile method
      run: docker build .
      working-directory: docker
