name: docker-test

on:
  pull_request:
    branches: [ main ]
    path:
      - ./scripts/build-latest-p2pdma-kernel
      - ./docker/Dockerfile

jobs:
  docker-test:
    name: docker-test
    runs-on: ubuntu-latest
    steps:
    - name: check out code using action/checkout
      uses: actions/checkout@v4.2.2
    - name: build package via the Dockerfile method
      run: docker build .
      working-directory: docker
