name: init-test

on:
  pull_request:
    branches: [ main ]
    paths:
    - './scripts/init-update'

jobs:
  init-test:
    name: init-test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v4.2.2
    - name: Run the init-release script
      run: ./scripts/init-update
    - name: Run the init-release script again
      run: ./scripts/init-update
