name: init-build-test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
    - './scripts/init-update'
    - './scripts/build-remote'

jobs:
  init-build-test:
    name: init-build-test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v4.2.2
    - name: Run the init-release script
      run: ./scripts/init-update
    - name: Run the init-release script again
      run: ./scripts/init-update
    - name: Run the build-remote script
      run: ./scripts/build-remote
      env:
        REMOTE_NAME: localhost
