name: kernel-tools

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '.wordlist.txt'
      - '.spellcheck.yml'

jobs:
  spell-check:
    name: spell-check
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v4.2.2
    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@v0.48.0
