name: spell-check

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.md'
    - '.wordlist.txt'
    - '.spellcheck.yml'

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v4.2.2
    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.48.0
